export const TOGGLE_THEME = 'TOGGLE_THEME';

export const POST_TRANSLATE_TEXT = 'POST_TRANSLATE_TEXT';
export const POST_TRANSLATE_TEXT_SUCCESS = 'POST_TRANSLATE_TEXT_SUCCESS';
export const POST_TRANSLATE_TEXT_FAILED = 'POST_TRANSLATE_TEXT_FAILED';

export const GET_LANGUAGES = 'GET_LANGUAGES';
export const GET_LANGUAGES_SUCCESS = 'GET_LANGUAGES_SUCCESS';
export const GET_LANGUAGES_FAILED = 'GET_LANGUAGES_FAILED';