export const POST_TRANSLATE_TEXT = 'POST_TRANSLATE_TEXT';
export const POST_TRANSLATE_TEXT_SUCCESS = 'POST_TRANSLATE_TEXT_SUCCESS';
export const POST_TRANSLATE_TEXT_FAILED = 'POST_TRANSLATE_TEXT_FAILED';


