export const LOCAL_STORAGE_KEY = 'THEME';

export const COLORS = {
	LIGHT_THEME_BACKGROUND_COLOR: '#FFF',
	DARK_THEME_BACKGROUND_COLOR: '#363537',
	LIGHT_THEME_TEXT_COLOR: '#000',
	DARK_THEME_TEXT_COLOR: '#FAFAFA',
	LIGHT_THEME_HEADER_COLOR: '#586efc',
	DARK_THEME_HEADER_COLOR: '#212121',
};
